# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dada.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1002, 713)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gagax = QtWidgets.QComboBox(self.centralwidget)
        self.gagax.setGeometry(QtCore.QRect(90, 90, 121, 61))
        self.gagax.setObjectName("gagax")
        self.gagax.addItem("")
        self.gagax.addItem("")
        self.gagax_2 = QtWidgets.QComboBox(self.centralwidget)
        self.gagax_2.setGeometry(QtCore.QRect(580, 100, 121, 61))
        self.gagax_2.setObjectName("gagax_2")
        self.gagax_2.addItem("")
        self.gagax_2.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(330, 430, 231, 131))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(380, 250, 111, 71))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1002, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.gagax.addItem("fuck")
        index = self.gagax.findText("0",QtCore.Qt.MatchFixedString)
        self.gagax.setCurrentIndex(index)

        self.pushButton.clicked.connect(self.pressed)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gagax.setItemText(0, _translate("MainWindow", "1"))
        self.gagax.setItemText(1, _translate("MainWindow", "0"))
        self.gagax_2.setItemText(0, _translate("MainWindow", "1"))
        self.gagax_2.setItemText(1, _translate("MainWindow", "0"))
        self.pushButton.setText(_translate("MainWindow", "Submit"))
        self.label.setText(_translate("MainWindow", "x or y"))


    def pressed(self):
        print(self.gagax.currentText())
        print(self.gagax_2.currentText())